#Requires -Version 5.1
<#
.SYNOPSIS
  将「沉浸式AI智能伴学系统」打包为 Windows 单机可执行程序（双击即用）。

.DESCRIPTION
  1. 构建 teacher-web-next 前端（Next 静态导出 + 同源相对路径 API）
  2. 将 out/ 复制到 Go embed 目录
  3. 编译为 dist-desktop/StudyAI教学系统.exe
  4. 附带 .env.example、使用说明、启动说明

.EXAMPLE
  .\scripts\build-desktop.ps1
  .\scripts\build-desktop.ps1 -SkipFrontend   # 仅重编后端（前端已构建过）
#>
param(
  [switch]$SkipFrontend,
  [string]$OutDir = ""
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
if (-not $OutDir) {
  $OutDir = Join-Path $Root "dist-desktop"
}

$WebEmbedDir = Join-Path $Root "backend\cmd\edu-server\web"
$FrontendDir = Join-Path $Root "teacher-web-next"
$BackendDir = Join-Path $Root "backend"
$ExeName = "StudyAI教学系统.exe"

Write-Host "==> 工作目录: $Root" -ForegroundColor Cyan
Write-Host "==> 输出目录: $OutDir" -ForegroundColor Cyan
Write-Host "==> 前端: teacher-web-next (Next.js + React Bits)" -ForegroundColor Cyan

# --- 1. Frontend ---
if (-not $SkipFrontend) {
  Write-Host "`n==> [1/3] 构建前端 teacher-web-next (静态导出 + 同源 API)..." -ForegroundColor Cyan
  Push-Location $FrontendDir
  # Next inlines NEXT_PUBLIC_* at build time. An empty process-env string is often
  # ignored, and .env.local would otherwise bake in http://127.0.0.1:18080.
  # .env.production.local beats .env.local for `next build` — force same-origin "".
  $prodEnvLocal = Join-Path $FrontendDir ".env.production.local"
  $wroteProdEnv = $false
  try {
    if (-not (Test-Path "node_modules")) {
      Write-Host "    npm install ..."
      npm install
      if ($LASTEXITCODE -ne 0) { throw "npm install failed" }
    }
    @(
      "# Generated by build-desktop.ps1 — do not commit. Same-origin API for embedded exe."
      "NEXT_PUBLIC_API_BASE_URL=same-origin"
    ) | Set-Content -Path $prodEnvLocal -Encoding UTF8
    $wroteProdEnv = $true
    $env:NEXT_PUBLIC_API_BASE_URL = "same-origin"
    npm run build
    if ($LASTEXITCODE -ne 0) { throw "frontend build failed" }
  }
  finally {
    if ($wroteProdEnv -and (Test-Path $prodEnvLocal)) {
      Remove-Item -Force $prodEnvLocal -ErrorAction SilentlyContinue
    }
    Pop-Location
    Remove-Item Env:NEXT_PUBLIC_API_BASE_URL -ErrorAction SilentlyContinue
  }

  $NextOut = Join-Path $FrontendDir "out"
  if (-not (Test-Path (Join-Path $NextOut "index.html"))) {
    throw "Next 静态导出未生成 out\index.html，请检查 teacher-web-next 的 output: 'export' 配置"
  }

  Write-Host "    复制 out/ 到 embed 目录..."
  if (Test-Path $WebEmbedDir) {
    Remove-Item -Recurse -Force $WebEmbedDir
  }
  New-Item -ItemType Directory -Path $WebEmbedDir | Out-Null
  Copy-Item -Recurse -Force (Join-Path $NextOut "*") $WebEmbedDir
}
else {
  Write-Host "`n==> [1/3] 跳过前端构建 (SkipFrontend)" -ForegroundColor Yellow
  if (-not (Test-Path (Join-Path $WebEmbedDir "index.html"))) {
    throw "embed web 目录缺少 index.html，请先不带 -SkipFrontend 完整构建一次"
  }
}

# --- 2. Backend / single exe ---
Write-Host "`n==> [2/3] 编译 Go 后端 (嵌入前端)..." -ForegroundColor Cyan
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
$ExePath = Join-Path $OutDir $ExeName

Push-Location $BackendDir
try {
  # CGO disabled: pure-Go sqlite (modernc.org/sqlite)
  $env:CGO_ENABLED = "0"
  go build -trimpath -ldflags "-s -w" -o $ExePath .\cmd\edu-server
  if ($LASTEXITCODE -ne 0) { throw "go build failed" }
}
finally {
  Pop-Location
  Remove-Item Env:CGO_ENABLED -ErrorAction SilentlyContinue
}

$sizeMB = [math]::Round((Get-Item $ExePath).Length / 1MB, 1)
Write-Host "    已生成: $ExePath ($sizeMB MB)" -ForegroundColor Green

# --- 3. Companion files ---
Write-Host "`n==> [3/3] 写入配置模板与说明..." -ForegroundColor Cyan

$envExample = @'
# 可选：与 exe 放在同一目录，命名为 .env
# 不配置也能启动；AI 对话可在网页「管理员 → 设置」里填写。

# 监听地址（默认本机 18080）
# EDU_ADDR=:18080

# 数据目录（默认：exe 同目录下的 data\）
# EDU_DATA_DIR=data

# 存储：sqlite（推荐）或 json
# EDU_STORAGE_DRIVER=sqlite

# 启动后是否自动打开浏览器（0=否）
# EDU_OPEN_BROWSER=1

# ---- LLM（OpenAI 兼容接口，也可在网页里配置）----
# 例：DeepSeek 官方
# YUNQUE_BASE_URL=https://api.deepseek.com
# YUNQUE_API_KEY=sk-你的密钥
#
# 例：本机 Ollama（无需 key）
# YUNQUE_BASE_URL=http://127.0.0.1:11434
# YUNQUE_API_KEY=
#
# 例：云雀 / 其它 OpenAI 兼容网关
# YUNQUE_BASE_URL=http://127.0.0.1:8080
# YUNQUE_API_KEY=
'@
Set-Content -Path (Join-Path $OutDir ".env.example") -Value $envExample.Trim() -Encoding UTF8

$readme = @'
# 沉浸式 AI 智能伴学系统 — 单机桌面版

## 怎么用（给最终用户）

1. 解压/复制整个文件夹到任意位置（可放 U 盘）。
2. 双击 **StudyAI教学系统.exe**。
3. 浏览器会自动打开 `http://127.0.0.1:18080`（若未打开，请手动访问）。
4. 使用演示账号登录：

| 角色 | 用户名 | 密码 |
|------|--------|------|
| 管理员 | admin | admin123456 |
| 教师 | teacher | teacher123456 |
| 学生 | student001 | student123456 |

5. **配置大模型（可选，不配也能进系统；AI 问答需要）**
   - 登录 **管理员** → 打开 **设置**
   - 填写 Base URL、模型名、API Key，勾选「启用模型调用」并保存
   - 或把本目录 `.env.example` 复制为 `.env`，按注释填写后重启程序

## 常见 LLM 填法

| 服务 | Base URL | 模型示例 | Key |
|------|----------|----------|-----|
| DeepSeek | `https://api.deepseek.com` | `deepseek-chat` | 官网 API Key |
| OpenAI | `https://api.openai.com` | `gpt-4o-mini` | sk-... |
| 本机 Ollama | `http://127.0.0.1:11434` | `qwen2.5:7b` 等 | 可留空 |
| 其它 OpenAI 兼容网关 | 网关地址（不要末尾 `/v1`，程序会拼 `/v1/chat/completions`） | 按网关文档 | 按网关文档 |

> 接口约定：OpenAI 兼容的 `POST {base_url}/v1/chat/completions`。

## 数据保存在哪

- 默认在 exe 同目录的 **`data\`**（SQLite：`data\study.db`）
- 换电脑时：连同整个文件夹一起拷走即可（含 data）
- 重置演示数据：关掉程序后删除 `data` 文件夹再启动

## 端口与防火墙

- 默认只监听本机 `18080`，**不需要公网服务器**
- 若要给局域网其他电脑访问：在 `.env` 设 `EDU_ADDR=0.0.0.0:18080`，并放行防火墙；对方访问 `http://你的IP:18080`

## 关闭程序

- 关闭黑色控制台窗口即可停止服务
- 或在任务管理器结束「StudyAI教学系统.exe」

## 系统要求

- Windows 10/11 x64
- 无需安装 Go / Node / Docker
- 使用在线大模型时需要能访问对应 API 的网络；完全离线可用 Ollama 等本机模型

## 说明

- 本包为「后端 + Next.js 教师/学生/管理 Web（React Bits 视觉）」一体；无需再单独起前端
- 未配置 LLM 时，系统会用内置启发式逻辑降级（可演示流程，质量弱于真实模型）
'@
Set-Content -Path (Join-Path $OutDir "使用说明.txt") -Value $readme.Trim() -Encoding UTF8

# Optional seed: do not copy live study.db (may contain local secrets). Fresh start seeds itself.

Write-Host "`n========================================" -ForegroundColor Green
Write-Host " 打包完成！" -ForegroundColor Green
Write-Host " 目录: $OutDir" -ForegroundColor Green
Write-Host " 双击: $ExeName" -ForegroundColor Green
Write-Host "========================================`n" -ForegroundColor Green
Write-Host "发给别人时：把整个 dist-desktop 文件夹打成 zip 即可。"
Write-Host "对方解压后双击 exe，用 admin / admin123456 登录并配置 LLM。"
